default:
  image: amazoncorretto:11.0.7
  before_script:
    - ': before_script'
    - chmod +x mvnw
    - export MAVEN_OPTS="-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/"

# Static Application Security Testing (SAST) is a frequently used Application Security (AppSec) tool,
# which scans an application’s source, binary, or byte code.
# https://www.microfocus.com/en-us/what-is/sast
include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  SAST_JAVA_VERSION: "11" # Required by SAST scanning

cache:
  key: maven-cache
  paths:
    - $CI_PROJECT_DIR/.m2/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - ./mvnw verify $MAVEN_OPTS
    - cat coverage-report/target/site/jacoco-aggregate/index.html | grep -o '<tfoot>.*</tfoot>'
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - coverage-report/target/site/jacoco-aggregate/*
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
        - "**/target/failsafe-reports/TEST-*.xml"
    expire_in: 1 hour

install:
  stage: build
  script:
    - ./mvnw clean install -DskipTests $MAVEN_OPTS
  artifacts:
    when: always
    paths:
      - client/target/generated-docs/client-api-docs.html
    expire_in: 1 hour

pages:
  stage: deploy
  script:
    - echo 'Cleaning old pages'
    - rm -rf public
    - ls -la
    - mkdir -p public/test-report && cp -r coverage-report/target/site/jacoco-aggregate/* public/test-report
    - mkdir -p public/rest-docs && cp client/target/generated-docs/client-api-docs.html public/rest-docs
    - echo 'Public directory content after copying files'
    - ls -la ./public
  artifacts:
    paths:
      - public
    expire_in: 1 hour
