spring:
  application:
    name: spring-cloud-eureka-client1
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
