server:
  http2:
    enabled: true
  port: 8443
  # The format used for the keystore. It could be set to JKS in case it is a JKS file
  ssl:
    key-store-type: PKCS12
    # The path to the keystore containing the certificate
    key-store: classpath:localhost.p12
    # The password used to generate the certificate
    key-store-password: password
    # The alias mapped to the certificate
    key-alias: localhost

logging:
  level:
    web: TRACE
    org.springframework.web: TRACE
    org.hibernate.SQL: DEBUG
