# In case of debugging, you can set a proper logging level.
#logging.level.root: DEBUG

spring:
  application:
    name: spring-cloud-eureka-reporting

server:
  port: 8000
  servlet:
    context-path: /reporting

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

warehouseMicroservice:
  eurekaName: spring-cloud-eureka-warehouse

shopMicroservice:
  eurekaName: spring-cloud-eureka-shop

factoryMicroservice:
  url: http://localhost:8300

# Default metric settings for all services
# (metrics should be ingested by the Admin microservice)
management:
  endpoints:
    jmx:
      exposure:
        exclude: shutdown
        include: '*'
    web:
      exposure:
        exclude:
        include: health,info,metrics,mappings
