spring:
  application:
    name: factory-microservice
  webflux:
    base-path: /factory

server:
  port: 8300

springdoc:
  swagger-ui:
    displayOperationId: true

orders:
  processing-time: 10

api:
  version: 0.0.1

# Default metric settings for all services
# (metrics should be ingested by the Admin microservice)
management:
  endpoints:
    jmx:
      exposure:
        exclude: shutdown
        include: '*'
    web:
      exposure:
        exclude:
        include: health,info,metrics
