spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

client2EurekaName:
  name: spring-cloud-eureka-service2

standaloneService:
  basePath: localhost:8100

apiDocumentation:
  name: spring-cloud-eureka-service2
  url: ''

# Default metric settings for all services
# (metrics should be ingested by the Admin microservice)
management:
  endpoints:
    jmx:
      exposure:
        exclude: shutdown
        include: '*'
    web:
      exposure:
        exclude:
        include: health,info,metrics
