spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

client2EurekaName:
  name: spring-cloud-eureka-client2

standaloneService:
  basePath: localhost:8003

apiDocumentation:
  name: spring-cloud-eureka-client2
  url: ''
