spring:
  application:
    name: standalone-service
  webflux:
    base-path: /standalone-microservice

server:
  port: 8300

api:
  version: 0.0.1

# Default metric settings for all services
# (metrics should be ingested by the Admin microservice)
management:
  endpoints:
    jmx:
      exposure:
        exclude: shutdown
        include: '*'
    web:
      exposure:
        exclude:
        include: health,info,metrics
